{
 "title": "Livepeer Payments Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Expected Payout in ETH",
   "type": "stat",
   "description": "Ticket Value received minus ticket value redeemed",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(livepeer_ticket_value_recv)-(sum(livepeer_value_redeemed) OR on() vector(0)))/10^9"
    }
   ]
  },
  {
   "title": "Expected Payout in ETH",
   "type": "graph",
   "description": "Ticket Value received minus ticket value redeemed",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "(sum(livepeer_ticket_value_recv)-(sum(livepeer_value_redeemed) OR on() vector(0)))/10^9"
    }
   ]
  },
  {
   "title": "# Tickets Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "# Tickets" }
   ],
   "targets": [
    { "expr": "sum(livepeer_tickets_recv)" }
   ]
  },
  {
   "title": "Payment Receive Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# Errors" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_payment_recv_errors)"
    }
   ]
  },
  {
   "title": "Value Redeemed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ETH (gwei)" }
   ],
   "targets": [
    { "expr": "livepeer_value_redeemed" }
   ]
  },
  {
   "title": "Ticket Redemption Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# Errors" }
   ],
   "targets": [
    {
     "expr": "livepeer_ticket_redemption_errors"
    }
   ]
  },
  {
   "title": "# Winning Tickets Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "# Winning Tickets" }
   ],
   "targets": [
    { "expr": "livepeer_winning_tickets_recv" }
   ]
  },
  {
   "title": "Transcoding Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "ETH (wei)" }
   ],
   "targets": [
    { "expr": "livepeer_transcoding_price" }
   ]
  },
  {
   "title": "Suggested Gas Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "ETH (gwei)" }
   ],
   "targets": [
    { "expr": "livepeer_suggested_gas_price" }
   ]
  }
 ]
}