{
 "title": "Nvidia GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "tags": [
  "gpu",
  "cluster",
  "hardware",
  "infrastructure"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "avg Temp.",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(temperature_gpu)" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature_gpu", "legendFormat": "{{gpu}}" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "avg(utilization_memory)" }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "utilization_memory", "legendFormat": "{{gpu}}" }
   ]
  },
  {
   "title": "avg GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "avg(utilization_gpu)" }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "utilization_gpu", "legendFormat": "{{gpu}}" }
   ]
  }
 ]
}