{
 "title": "Orchestrator Overview",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Daily Projected Income in ETH",
   "type": "stat",
   "description": "Based on data from the previous 7 days",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(livepeer_ticket_value_recv[7d])*60*60*24)/10^9"
    }
   ]
  },
  {
   "title": "Expected Payout in ETH",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(livepeer_ticket_value_recv)-(sum(livepeer_value_redeemed) OR on() vector(0)))/10^9"
    }
   ]
  },
  {
   "title": "# Orchestrators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_versions{node_type=\"orch\"})"
    }
   ]
  },
  {
   "title": "Orchestrator Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"}) / sum(livepeer_max_sessions_total{node_type=\"orch\"}) * 100"
    }
   ]
  },
  {
   "title": "# Orchestrators Sessions",
   "type": "graph",
   "description": "Calculated max sessions based on GPU memory",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"})",
     "legendFormat": "Current Sessions"
    }
   ]
  },
  {
   "title": "# Orchestrator Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"})"
    }
   ]
  },
  {
   "title": "Sessions by Profile",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(livepeer_segment_transcoded_total[30m])/ on() group_left() sum(increase(livepeer_segment_transcoded_total[30m]))",
     "legendFormat": "{{profiles}}"
    }
   ]
  },
  {
   "title": "Winning Tickets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(livepeer_winning_tickets_recv OR on() vector(0))"
    }
   ]
  },
  {
   "title": "# Ticket Value Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livepeer_ticket_value_recv/10^9"
    }
   ]
  },
  {
   "title": "VRAM Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "memory_used/memory_total", "legendFormat": "{{gpu}}" }
   ]
  },
  {
   "title": "Suggested Gas Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "livepeer_suggested_gas_price", "legendFormat": "Sug. Gas Price" }
   ]
  },
  {
   "title": "Transcode Score (Average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_score_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_score_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{profiles}}"
    }
   ]
  },
  {
   "title": "Transcode Times (Average)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_time_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{profiles}}"
    }
   ]
  },
  {
   "title": "Source Duration (Average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_source_segment_duration_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_source_segment_duration_seconds_count{node_type=\"orch\"}[1m])"
    }
   ]
  },
  {
   "title": "Download Times (Average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_download_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_download_time_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}